name: Check and Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [released]
permissions: read-all
jobs:
  check:
    name: Check on python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.12'
          - '3.11'
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Lint
        run: make lint format
        env:
          PYTHON: ${{ steps.python.outputs.python-path }}
      - name: Test
        run: make test
        env:
          PYTHON: ${{ steps.python.outputs.python-path }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Building package
        run: make srcdist wheel
        env:
          PYTHON: ${{ steps.python.outputs.python-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/*
          if-no-files-found: error
  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    needs: [build]
    if: github.repository == 'Eeems-Org/python-libremarkable' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/libremarkable
    steps:
      - name: Download pip packages
        id: download
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ steps.download.outputs.download-path }}
